version: '3.7'
services:
  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    container_name: redpanda
    ports:
      - 9092:9092
      - 29092:29092
      - 9644:9644
  prometheus:
    image: prom/prometheus:v2.27.1
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
      - "GF_INSTALL_PLUGINS=grafana-worldmap-panel"
      - /var/lib/grafana
      - ./docker/redpanda/dashboards:/dashboards:ro
    ports:
      - 3000:3000
